spring:

  profiles:
    active: local

  datasource:
    url: jdbc:mariadb://localhost/DB?characterEncoding=UTF-8
    username: june1
    password: qweQWE123!@#
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    open-in-view: false

mybatis:
  # 패키지 이름을 생략할 수 있도록 해준다.
  type-aliases-package: june1.db.domain
  # 언더바를 카멜로 자동 변경해준다.
  configuration.map-underscore-to-camel-case: true
  # xml 파일의 위치를 바꾸고 싶다면..
  #mapper-locations: classpath:mybatis/mapper/**/*.xml

logging:
  level:
    org.springgramework.jdbc: debug
    june1.db.repository.mybatis: trace

