spring:

  #-------------------------------
  # JSP
  #-------------------------------
  mvc.view:
    prefix: /WEB-INF/views/
    suffix: .jsp

  #-------------------------------
  # DataSource
  #-------------------------------
  datasource:
    url: jdbc:oracle:thin:@192.168.0.2:1521:xe
    username: june1
    password: qweQWE123!@#
    driver-class-name: oracle.jdbc.OracleDriver

#-------------------------------
# MyBatis
#-------------------------------
mybatis:
  # 타입 정보를 사용할 때 적어주어야 하는 패키지 이름을 생략할 수 있다.
  # 지정한 값이 가리키는 패키지와 그 하위 패키지는 자동으로 인식된다.
  # xml 파일의 resultType 속성에 적용된다.
  type-aliases-package: june1.study.java.jsp_mybatis_oracle.domain

  # xml 파일을 원하는 위치에 두기 위한 정보를 설정한다.
  mapper-locations: classpath:mybatis/mapper/**/*.xml

  # DB 의 underscore 규칙을 Java 의 camel-case 로 변환해 준다.
  configuration.map-underscore-to-camel-case: true

#-------------------------------
# Logging
#-------------------------------
logging:
  level:
    june1.study.java.jsp_mybatis_oracle.repository.mybatis: trace
