spring:
  datasource:
    jdbc-url: jdbc:mariadb://localhost:3306/test?characterEncoding=UTF-8&serverTimezone=UTC
    username: june1
    password: qweQWE123!@#
    driver-class-name: org.mariadb.jdbc.Driver

  quartz:
    datasource:
      jdbc-url: jdbc:mariadb://localhost:3306/QUARTZ?characterEncoding=UTF-8&serverTimezone=UTC
      username: june1
      password: qweQWE123!@#
      driver-class-name: org.mariadb.jdbc.Driver

  batch:
    datasource:
      jdbc-url: jdbc:mariadb://localhost:3306/BATCH?characterEncoding=UTF-8&serverTimezone=UTC
      username: june1
      password: qweQWE123!@#
      driver-class-name: org.mariadb.jdbc.Driver

    job:
      # 애플리케이션 실행 시 잡 실행되지 않게 하기
      #enabled: true
      enabled: false

      # 애플리케이션 실행 시 실행을 원하는 잡을 명시하기
      # 쉼표로 구분하여 순서대로 실행
      # enabled 가 true 일 때 작용..
      #names: ${job.name:NONE}
      names: 배치_잡

args:
  group: ${group:NONE}
